# Generated by Django 5.1.2 on 2024-12-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paragraph_generator', '0002_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedcontent',
            name='grade_level',
        ),
        migrations.RemoveField(
            model_name='generatedcontent',
            name='style',
        ),
        migrations.RemoveField(
            model_name='generatedcontent',
            name='tone',
        ),
    ]
