# Generated by Django 5.1.2 on 2024-12-16 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paragraph_generator', '0003_remove_generatedcontent_grade_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedcontent',
            name='user',
        ),
    ]
