# Generated by Django 5.1.2 on 2024-12-16 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paragraph_generator', '0004_remove_generatedcontent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
    ]
